coverage:
  status:
    project:
      default: false
      tests:
        paths: "tests/"
        target: 100%
      app:
        paths: "app/"
        target: 75%
      tools:
        paths: "tools/"
        target: 85%
